#%RAML 1.0 NamedExample
value:
  Country: Ethiopia
  CountryCode: +251
  Province: Tigtray
  city: Addis Ababa
  CityCode: +251-9
  Lat: 0
  Lon: 0
  Confirmed: 1
  Deaths: 0
  Recovered: 0
  Active: 0
  Date: 2020-01-30T00:00:00Z

